typeset -gU path
path=(
    $path
    /opt/local/*/sbin(N-/)
    /opt/local/*/bin(N-/)
    /opt/*/sbin(N-/)
    /opt/*/bin(N-/)
    /opt/sbin(N-/)
    /opt/bin(N-/)
    /usr/local/*/sbin(N-/)
    /usr/local/*/bin(N-/)
    /usr/*/sbin(N-/)
    /usr/*/bin(N-/)
    /usr/ucb(N-/)
    /usr/sbin(N-/)
    /usr/bin(N-/)
    /sbin(N-/)
    /bin(N-/)
)
