_sources $(dirname ${(%):-%N})/profile.d/*.zsh(N-.)
_sources $DOTFILES_DIR/modules/*/zsh.profile(N-.)
_sources $(dirname ${(%):-%N})/profile.d-post/*.zsh(N-.)
_sources ~/.zsh?*/.zprofile(N-.)
_sources ~/.zsh?*/profile.d/*.zsh(N-.)
