manpath=(
    ${HOME}/man/ja(N-/)
    ${HOME}/share/man/ja(N-/)
    ${HOME}/man(N-/)
    ${HOME}/share/man(N-/)
    ${HOME}/opt/*/share/man/ja(N-/)
    ${HOME}/opt/*/man/ja(N-/)
    ${HOME}/opt/*/share/man(N-/)
    ${HOME}/opt/*/man(N-/)
    $manpath
)
