_sources $DOTFILES_SOURCE_DIR/zsh/zprofile.d/*.zsh(N-.)
_sources $DOTFILES_DIR/modules/*/zprofile.zsh(N-.)
_sources $DOTFILES_SOURCE_DIR/zsh/zprofile.d-post/*.zsh(N-.)
_sources ~/.zsh?*/.zprofile(N-.)
_sources ~/.zsh?*/zprofile.d/*.zsh(N-.)
